package com.example.anoreplier

class FileIO {

    companion object{
        val OUTPUT_DIRECTORY: String=("/storage/emulated/0/Android/data/com.AnoReplier")
        val MESSAGE_FILE_NAME:String=("Message.txt")
        val REPLY_FILE_NAME:String=("Replies.txt")

        val DEFAULT_MESSAGE:String="Currently Unavaliable.Error code-404\nAutomated message Generated by Anoreplier\n"
        val DEFAULT_TOTAL_REPLIES:Int=0

    }
}